// this file is generated by program
#ifndef __WIN_ICMP_H_BA04A306B42DAB730B48A37E230991D9__
#define __WIN_ICMP_H_BA04A306B42DAB730B48A37E230991D9__

#include <win_types.h>

#undef __WINLIB_INNER_INCLUDE__
#define __WINLIB_INNER_INCLUDE__
#include <win_inner.h>
#undef __WINLIB_INNER_INCLUDE__



#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

WINLIB_API void* init_icmp_sock(int type);
WINLIB_API void free_icmp_sock(void** ppsock);
WINLIB_API int send_icmp_request(void* psock,const char* ip);
WINLIB_API int icmp_complete_read(void* psock);
WINLIB_API int icmp_complete_write(void* psock);
WINLIB_API HANDLE get_icmp_read_evt(void* psock);
WINLIB_API HANDLE get_icmp_write_evt(void* psock);
WINLIB_API int icmp_is_read_mode(void* psock);
WINLIB_API int icmp_is_write_mode(void* psock);
WINLIB_API int icmp_send_cnt(void* psock);
WINLIB_API int recv_icmp_response(void* psock,uint64_t* pval);

#ifdef __cplusplus
};
#endif /* __cplusplus*/

#endif /* __WIN_ICMP_H_BA04A306B42DAB730B48A37E230991D9__ */
