// this file is generated by program
#ifndef __WIN_PING_H_BA04A306B42DAB730B48A37E230991D9__
#define __WIN_PING_H_BA04A306B42DAB730B48A37E230991D9__

#include <win_types.h>

#undef __WINLIB_INNER_INCLUDE__
#define __WINLIB_INNER_INCLUDE__
#include <win_inner.h>
#undef __WINLIB_INNER_INCLUDE__



#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

WINLIB_API void* init_ping_sock(int type);
WINLIB_API void free_ping_sock(void** ppsock);
WINLIB_API int send_ping_request(void* psock,const char* ip);
WINLIB_API int ping_complete_read(void* psock);
WINLIB_API int ping_complete_write(void* psock);
WINLIB_API HANDLE get_ping_read_evt(void* psock);
WINLIB_API HANDLE get_ping_write_evt(void* psock);
WINLIB_API int ping_is_read_mode(void* psock);
WINLIB_API int ping_is_write_mode(void* psock);
WINLIB_API int ping_send_cnt(void* psock);
WINLIB_API int recv_ping_response(void* psock,uint64_t* pval);

#ifdef __cplusplus
};
#endif /* __cplusplus*/

#endif /* __WIN_PING_H_BA04A306B42DAB730B48A37E230991D9__ */
