// this file is generated by program
#ifndef __WIN_PE_H_EC712AAB2E326048D5B51B0840FC5F82__
#define __WIN_PE_H_EC712AAB2E326048D5B51B0840FC5F82__


#undef __WINLIB_INNER_INCLUDE__
#define __WINLIB_INNER_INCLUDE__
#include <win_inner.h>
#undef __WINLIB_INNER_INCLUDE__


#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

WINLIB_API void* memory_load_module(void* ptr, int memsize);
WINLIB_API void memory_free_module(void* pmod);
WINLIB_API void* memory_get_proc_addr(void* pmod,const char* procname);
WINLIB_API void* memory_get_resource_addr(void* pmod,const char* resid);


#ifdef __cplusplus
};
#endif /* __cplusplus*/

#endif /* __WIN_PE_H_EC712AAB2E326048D5B51B0840FC5F82__ */
