// this file is generated by program
#ifndef __BASE64_CODE_H_7B6C1364C37F57F363C594746998F806__
#define __BASE64_CODE_H_7B6C1364C37F57F363C594746998F806__

#include <cmn_err.h>


#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

WINLIB_API int encode_base64(unsigned char* pbuffer,int insize, char* pencbuf,int outsize);
WINLIB_API int decode_base64(char* pencbuf, int insize,unsigned char* pbuffer, int outsize);
WINLIB_API int base64_splite_line(char* pencbuf,int inlen,int linelen,char**ppencline,int *poutsize);
WINLIB_API int base64_compact_line(char* pencbuf,int inlen,char** ppencnoline, int* poutsize);


#ifdef __cplusplus
};
#endif /* __cplusplus*/

#endif /* __BASE64_CODE_H_7B6C1364C37F57F363C594746998F806__ */
