// this file is generated by program
#ifndef __UX_DBG_H_D2F5FDC5907F1670D441E9B6360C0C58__
#define __UX_DBG_H_D2F5FDC5907F1670D441E9B6360C0C58__

#include <ux_err.h>


typedef struct __proc_mem_info {
	uint64_t m_startaddr;
	uint64_t m_endaddr;
	char m_file[512];	
} proc_mem_info_t,*pproc_mem_info_t;


#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

int backtrace_safe(int idx, void*** pppbacks, int *psize);
/***********************************************
*  pid >= 0 for process id pid == -1 for current process < -1 for free ppmem psize
***********************************************/
int get_proc_mem_info(int pid,pproc_mem_info_t *ppmem,int *psize);

#ifdef __cplusplus
};
#endif /* __cplusplus*/

#endif /* __UX_DBG_H_D2F5FDC5907F1670D441E9B6360C0C58__ */
