// this file is generated by program
#ifndef __UX_PING_H_5F594F961CD6DF4E8F5846617B2EC30C__
#define __UX_PING_H_5F594F961CD6DF4E8F5846617B2EC30C__

#include <ux_err.h>


#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

void* init_ping_sock(int type);
void free_ping_sock(void** ppsock);
int send_ping_request(void* psock,const char* ip);
int ping_complete_read(void* psock);
int ping_complete_write(void* psock);
int get_ping_evt(void* psock);
int ping_is_read_mode(void* psock);
int ping_is_write_mode(void* psock);
int recv_ping_response(void* psock,uint64_t* pval);


#ifdef __cplusplus
};
#endif /* __cplusplus*/

#endif /* __UX_PING_H_5F594F961CD6DF4E8F5846617B2EC30C__ */
