// spaceshipsvr.idl: spaceshipsvr 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(spaceshipsvr.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(ace53709-fa8f-452e-99e8-d57985c53717),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IATLSpaceship : IDispatch
{
	[id(1)] HRESULT CallStartFleet([in]float fStarDate, [out, retval]BSTR* pbstrRecipient);
};

[
	object,
	uuid(692D03A4-C689-11CE-B337-88EA36DE9E4E),
	dual,
	helpstring("IMotion interface")
]
interface IMotion : IDispatch
{
	[id(1)] HRESULT Fly();
	[id(2)] HRESULT GetPosition([out, retval] long* nPosition);
};

[
	object,
	uuid(692D03A5-C689-11CE-B337-88EA36DE9E4E),
	helpstring("IVisual interface")
]
interface IVisual : IUnknown
{
	[id(1)] HRESULT Display();
};

[
	uuid(c1b1ca83-b9bf-4e99-8be6-cc5d16b62570),
	version(1.0),
]
library spaceshipsvrLib
{
	importlib("stdole2.tlb");
	[
		uuid(77562bec-dd02-4645-ada1-d0c254a98de7)
	]
	coclass ATLSpaceship
	{
		[default] interface IATLSpaceship;
	};
};

import "shobjidl.idl";
