// this file is generated by program
#ifndef __PINGCAP_H_DB0F356DE42D03B030B243803FD3981E__
#define __PINGCAP_H_DB0F356DE42D03B030B243803FD3981E__

#include <win_ping.h>
#include "evcombo.h"
#include <win_libev.h>
#include <Windows.h>

#pragma warning(push)
#pragma warning(disable:4577)
#pragma warning(disable:4530)

#include <vector>
#include <string>
#pragma warning(pop)


class PingCap : public IEvRunner
{
public:
	PingCap(int pingtype,const char* ip,int times,int timeout,int nexttime,void* pev,IEvCombo* pcombo);
	virtual ~PingCap();
	int set_timeout(int timeout);
	int set_nexttime(int nexttime);
	int set_times(int times);
	virtual int start();
	virtual int get_result(std::string& vstr);
private:
	static int ping_callback(HANDLE hd,libev_enum_event_t event,void* pevmain,void* args);
	static int ping_timeout(uint64_t guid,libev_enum_event_t event,void* pevmain,void* args);

	void __release_resource();

	void __remove_tmout();
	void __remove_tmnext();
	void __remove_rd();
	void __remove_wr();

	int __insert_tmout();
	int __insert_tmnext();
	int __insert_rd();
	int __insert_wr();

	void __call_remove();
	void __call_notify();

	int __push_now_str(uint64_t val);
	int __collect_value_and_next(uint64_t val);
	int __inc_and_check_next();

	int __get_now_str(std::string& tstr,uint64_t val);
	int __restart();

	int _callback_func(HANDLE hd);
	int __timeout(uint64_t guid);

private:
	void* m_sock;
	std::string m_ip;


	int m_pingtype;
	int m_times;
	int m_timeout;
	int m_nexttime;
	int m_curtime;
	int m_reserv1;

	HANDLE m_rdevt;
	HANDLE m_wrevt;
	uint64_t m_tmoutguid;
	uint64_t m_tmnextguid;

	int m_insertrd;
	int m_insertwr;
	int m_inserttmout;
	int m_inserttmnext;


	void* m_evmain;
	IEvCombo* m_combo;
	std::vector<std::string> m_pingval;
};


#endif /* __PINGCAP_H_DB0F356DE42D03B030B243803FD3981E__ */
