// this file is generated by program
#ifndef __PINGTOTAL_H_380557163CB18CB433739E2A9828B75C__
#define __PINGTOTAL_H_380557163CB18CB433739E2A9828B75C__

#include "pingcap.h"
#include <windows.h>


class PingTotal
{
public:
	PingTotal(int timeout,int nexttime,int times,int verbose);
	virtual ~PingTotal();
	int add_host(const char* ip);
	int get_mean(int idx, char** ppipstr,uint64_t* pval);
	int loop(HANDLE exithd);
	int get_succ_ratio(int idx, char** ppipstr,double* pratio);
private:
	int __min2(int a, int b);
private:	
	std::vector<PingCap*>* m_vec;
	std::vector<char*>* m_ipvec;
	int m_verbose;
	int m_timeout;
	int m_nexttime;
	int m_times;
};

#endif /* __PINGTOTAL_H_380557163CB18CB433739E2A9828B75C__ */
