// this file is generated by program
#ifndef __PIPE_CLI_COMM_H_4F82288E4830F106236A252D2CD3E3F8__
#define __PIPE_CLI_COMM_H_4F82288E4830F106236A252D2CD3E3F8__

#include "pipe_comm.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

#ifdef __cplusplus
};
#endif /* __cplusplus*/

class pipe_cli_comm
{
public:
	pipe_cli_comm(char* pipename,int timeout);
	~pipe_cli_comm();
	int init();
	int is_read_mode();
	int is_write_mode();
	HANDLE get_read_evt();
	HANDLE get_write_evt();
	int read_json(jvalue** ppj);
	int write_json(jvalue* pj);	
	int complete_write(void);
	int complete_read(void);
private:
	void __uninit();
private:
	pipe_comm* m_pipe;
	char* m_pipename;
	int m_inited;
	int m_timeout;

};

#endif /* __PIPE_CLI_COMM_H_4F82288E4830F106236A252D2CD3E3F8__ */
