// this file is generated by program
#ifndef __PIPE_COMM_H_C7ABCD762C503EBB441C3363BED9EC7D__
#define __PIPE_COMM_H_C7ABCD762C503EBB441C3363BED9EC7D__

#include <jvalue.h>
#include <vector>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

#ifdef __cplusplus
};
#endif /* __cplusplus*/

class pipe_comm
{
public:
	pipe_comm(void* ppipe,char* pipename);
	~pipe_comm();
	int init();
	int is_read_mode();
	int is_write_mode();
	HANDLE get_read_evt();
	HANDLE get_write_evt();
	int read_json(jvalue** ppj);
	int write_json(jvalue* pj);	
	int complete_write(void);
	int complete_read(void);

private:
	void __uninit();
	uint32_t __get_json_size();
	int __inner_read();
	int __inner_write();
private:
	void* m_pipe;
};

#endif /* __PIPE_COMM_H_C7ABCD762C503EBB441C3363BED9EC7D__ */
