// this file is generated by program
#ifndef __SOCK_COMM_H_344CBE184C45B5FE27EE00DDA0BF0BDF__
#define __SOCK_COMM_H_344CBE184C45B5FE27EE00DDA0BF0BDF__

#include <jvalue.h>

#ifdef  _MSC_VER
#if  _MSC_VER >= 1929
#pragma warning(push)
#pragma warning(disable:4577)
#endif
#endif /* _MSC_VER*/

#include <vector>

#ifdef  _MSC_VER
#if  _MSC_VER >= 1929
#pragma warning(pop)
#endif
#endif /* _MSC_VER*/


#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

#ifdef __cplusplus
};
#endif /* __cplusplus*/

class sock_comm
{
public:
	sock_comm(void* psock);
	~sock_comm();
	int read_json(jvalue** ppj);
	int write_json(jvalue* pj);
	HANDLE get_read_evt();
	HANDLE get_write_evt();
	int is_write_mode();
	int is_read_mode();
	int is_closed();
	int init();
	int complete_write();
	int complete_read();

private:
	void __uninit();
	int __get_json_size();
	int __inner_read();
	int __inner_write();
private:
	void* m_sock;
	char* m_prdbuf;
	char* m_pwrbuf;
	std::vector<char*> *m_pbufs;
	std::vector<int> *m_pbuflens;
	int m_inited;
	int m_rdlen;
	int m_rdsize;
	int m_needlen;
	int m_wrlen;
	int m_reserv1;
};

#endif /* __SOCK_COMM_H_344CBE184C45B5FE27EE00DDA0BF0BDF__ */
