// this file is generated by program
#ifndef __SOCK_SVR_COMM_H_E949E02FEF8C456956702E329CE743C4__
#define __SOCK_SVR_COMM_H_E949E02FEF8C456956702E329CE743C4__

#include "sock_comm.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus*/

#ifdef __cplusplus
};
#endif /* __cplusplus*/

class sock_svr_comm
{
public:
	sock_svr_comm(char* ipaddr, int port);
	~sock_svr_comm();
	int init();
	int is_accept_mode();
	HANDLE get_accept_evt();
	int complete_accept();
	sock_comm* get_accept();
private:
	void __uninit();
private:	
	void* m_realsock;
	void* m_chldsock;
	char* m_ipaddr;
	int m_port;
	int m_inited;
};


#endif /* __SOCK_SVR_COMM_H_E949E02FEF8C456956702E329CE743C4__ */
