// this file is generated by program
#ifndef __PINGTOTAL_H_EC36418B5D1A9A1B4F8CD5D99D5526C4__
#define __PINGTOTAL_H_EC36418B5D1A9A1B4F8CD5D99D5526C4__

#include "pingcap.h"
#include <ux_err.h>
#include <map>

class PingTotal
{
public:
	PingTotal(int timeout,int nexttime,int times,int verbose);
	virtual ~PingTotal();
	int add_host(const char* ip);
	int get_mean(int idx, char** ppipstr,uint64_t* pval);
	int loop(int exithd);
	int get_succ_ratio(int idx, char** ppipstr,double* pratio);
private:
	int __min2(int a, int b);
	PingCap* __find_pingcap(int fd);
	int __insert_pingcap(int fd,PingCap* pv);
	int __remove_pingcap(int fd);
private:	
	std::vector<PingCap*>* m_vec;
	std::vector<char*>* m_ipvec;
	std::map<int,PingCap*>* m_findmap;
	int m_verbose;
	int m_timeout;
	int m_nexttime;
	int m_times;
};

#endif /* __PINGTOTAL_H_EC36418B5D1A9A1B4F8CD5D99D5526C4__ */
