
CURDIR=$(MAKEDIR)
TOPDIR=$(CURDIR)
DYNAMICDIR=$(TOPDIR)\dynamiclib
STATICDIR=$(TOPDIR)\staticlib

CC      = cl.exe
LD      = link.exe
AR      = lib.exe
RM      = del
PYTHON  = python.exe
GIT     = git.exe
CP      = copy /Y
GOBIN   = go.exe

!IFDEF UNICODE_MODE
!IF $(UNICODE_MODE) != 0
UNICODE_CFLAGS=-DUNICODE -D_UNICODE
!ELSE
UNICODE_CFLAGS=
!ENDIF
!ELSE
UNICODE_CFLAGS=
!ENDIF


!IFDEF MAKEVERBOSE
!IF $(MAKEVERBOSE) != 0
QUIETCMD=
NOLOGO_CFLAGS=
NOLOGO_LDFLAGS=
NOLOGO_MAKEFLAGS=
GIT_VERBOSE=
!ELSE
QUIETCMD=@
NOLOGO_CFLAGS=/nologo
NOLOGO_LDFLAGS=/nologo
NOLOGO_MAKEFLAGS=/NOLOGO
GIT_VERBOSE=--quiet
!ENDIF
!ELSE
QUIETCMD=@
NOLOGO_CFLAGS=/nologo
NOLOGO_LDFLAGS=/nologo
NOLOGO_MAKEFLAGS=/NOLOGO
GIT_VERBOSE=--quiet
!ENDIF

!IFDEF STATICLIB
!IF $(STATICLIB) != 0
STATIC_LIB_CFLAGS=/MT
EXTARGSLIB_VALUE=1
WINLIB_VALUE=1

INC_LDFLAGS = "$(STATICDIR)\classdll.lib"

!ELSE
STATIC_LIB_CFLAGS=-DCLASS_DLL_IMPORT /MT
EXTARGSLIB_VALUE=0
WINLIB_VALUE=0

INC_LDFLAGS = "$(DYNAMICDIR)\classdll.lib"

!ENDIF
!ELSE
STATIC_LIB_CFLAGS=-DCLASS_DLL_IMPORT /MT
EXTARGSLIB_VALUE=0
WINLIB_VALUE=0

INC_LDFLAGS = "$(DYNAMICDIR)\classdll.lib"
!ENDIF

INC_CFLAGS = /I"$(TOPDIR)\classdll" 
COM_CFLAGS = /Wall /wd"4710"
REL_CFLAGS = 
DBG_CFLAGS = /Zi /Od


#INC_LDFLAGS = "$(TOPDIR)\winlib\winlib.lib" Advapi32.lib
REL_LDFLAGS = 

CFLAGS  = $(UNICODE_CFLAGS) $(NOLOGO_CFLAGS) $(STATIC_LIB_CFLAGS) $(INC_CFLAGS) $(COM_CFLAGS) $(REL_CFLAGS) $(DBG_CFLAGS)
LDFLAGS = $(NOLOGO_LDFLAGS) $(INC_LDFLAGS) $(REL_LDFLAGS)

SOURCES=main.cpp
OBJECTS=$(SOURCES:.cpp=.obj)

all:main.exe

!IFDEF STATICLIB
!IF $(STATICLIB) != 0
main.exe:$(OBJECTS) $(STATICDIR)\classdll.lib
	$(QUIETCMD) echo "call static $(OBJECTS)"
	$(QUIETCMD)$(LD) -out:$@  $(LDFLAGS)  $(OBJECTS)
	$(QUIETCMD)echo "use static lib"
!ELSE
main.exe:$(OBJECTS)  $(DYNAMICDIR)\classdll.dll
	$(QUIETCMD) echo "call dynamic $(OBJECTS)"
	$(QUIETCMD)$(LD) -out:$@ $(LDFLAGS) $(OBJECTS)
		$(QUIETCMD) copy /Y $(DYNAMICDIR)\classdll.dll $(CURDIR)\classdll.dll
	$(QUIETCMD)echo "use dynamic lib"
!ENDIF	

!ELSE
main.exe:$(OBJECTS)  $(DYNAMICDIR)\classdll.dll
	$(QUIETCMD) echo "call dynamic $(OBJECTS)"
	$(QUIETCMD)$(LD) -out:$@ $(LDFLAGS) $(OBJECTS)
	$(QUIETCMD) copy /Y $(DYNAMICDIR)\classdll.dll $(CURDIR)\classdll.dll
	$(QUIETCMD)echo "use dynamic lib"
!ENDIF


.cpp.obj:
	$(QUIETCMD)$(CC) $(CFLAGS) -c -Fo$@ $<


	




$(DYNAMICDIR)\classdll.dll:
	$(QUIETCMD)cd $(TOPDIR)\classdll && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=0 /f makefile.win all && cd "$(CURDIR)"






$(STATICDIR)\classdll.lib:
	$(QUIETCMD)cd $(TOPDIR)\classdll && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=1 /f makefile.win all && cd "$(CURDIR)"



clean_classdll:
	$(QUIETCMD)cd $(TOPDIR)\classdll && $(MAKE) $(NOLOGO_MAKEFLAGS) /f makefile.win clean && cd "$(CURDIR)"


clean:clean_classdll
	$(QUIETCMD) $(RM) *.exe *.obj 2>NUL
	$(QUIETCMD) $(RM) *.pdb *.ilk 2>NUL
	$(QUIETCMD) $(RM) *.dll 2>NUL
