
CURDIR=$(MAKEDIR)
TOPDIR=$(CURDIR)\..\..
DYNAMICDIR=$(TOPDIR)\dynamiclib
STATICDIR=$(TOPDIR)\staticlib

CC      = cl.exe
LD      = link.exe
AR      = lib.exe
RM      = del
PYTHON  = python.exe
GIT     = git.exe
CP      = copy /Y
GOBIN   = go.exe

!IFDEF UNICODE_MODE
!IF $(UNICODE_MODE) != 0
UNICODE_CFLAGS=-DUNICODE -D_UNICODE
!ELSE
UNICODE_CFLAGS=
!ENDIF
!ELSE
UNICODE_CFLAGS=
!ENDIF


!IFDEF MAKEVERBOSE
!IF $(MAKEVERBOSE) != 0
QUIETCMD=
NOLOGO_CFLAGS=
NOLOGO_LDFLAGS=
NOLOGO_MAKEFLAGS=
GIT_VERBOSE=
!ELSE
QUIETCMD=@
NOLOGO_CFLAGS=/nologo
NOLOGO_LDFLAGS=/nologo
NOLOGO_MAKEFLAGS=/NOLOGO
GIT_VERBOSE=--quiet
!ENDIF
!ELSE
QUIETCMD=@
NOLOGO_CFLAGS=/nologo
NOLOGO_LDFLAGS=/nologo
NOLOGO_MAKEFLAGS=/NOLOGO
GIT_VERBOSE=--quiet
!ENDIF

!IFDEF STATICLIB
!IF $(STATICLIB) != 0
STATIC_LIB_CFLAGS=-DWINLIB_STATIC_EXPORT /MT
EXTARGSLIB_VALUE=1
WINLIB_VALUE=1

INC_LDFLAGS = "$(STATICDIR)\extargslib.lib" "$(STATICDIR)\winlib.lib" "$(STATICDIR)\json.lib"

!ELSE
STATIC_LIB_CFLAGS=-DWINLIB_DLL_IMPORT /MT
EXTARGSLIB_VALUE=0
WINLIB_VALUE=0

INC_LDFLAGS = "$(DYNAMICDIR)\extargslib.lib" "$(DYNAMICDIR)\winlib.lib" "$(DYNAMICDIR)\json.lib"

!ENDIF
!ELSE
STATIC_LIB_CFLAGS=-DWINLIB_DLL_IMPORT /MT
EXTARGSLIB_VALUE=0
WINLIB_VALUE=0

INC_LDFLAGS = "$(DYNAMICDIR)\extargslib.lib" "$(DYNAMICDIR)\winlib.lib" "$(DYNAMICDIR)\json.lib"
!ENDIF

INC_CFLAGS = /I"$(CURDIR)\..\loglib" /I"$(CURDIR)\..\proto_win" /I"$(TOPDIR)\common\extargslib" /I"$(TOPDIR)\winlib" /I"$(TOPDIR)\common\jsonlib" /I"$(TOPDIR)\common"
COM_CFLAGS = /Wall /wd"4820" /wd"4668" /wd"4127" /wd"4510" /wd"4512" /wd"4610" /wd"4710" /wd"5045" /wd"4530" /wd"4577"
REL_CFLAGS = 
DBG_CFLAGS = /Zi /Od 


#INC_LDFLAGS = "$(TOPDIR)\winlib\winlib.lib" Advapi32.lib
REL_LDFLAGS = 

CFLAGS  = $(UNICODE_CFLAGS) $(NOLOGO_CFLAGS) $(STATIC_LIB_CFLAGS) $(INC_CFLAGS) $(COM_CFLAGS) $(REL_CFLAGS) $(DBG_CFLAGS)
LDFLAGS = $(NOLOGO_LDFLAGS) $(INC_LDFLAGS) $(REL_LDFLAGS)

SOURCES=main.cpp log_file.cpp log_rcv.cpp
OBJECTS=$(SOURCES:.cpp=.obj)

all:svrlog.exe

!IFDEF STATICLIB
!IF $(STATICLIB) != 0
svrlog.exe:$(OBJECTS) $(STATICDIR)\winlib.lib $(STATICDIR)\json.lib $(STATICDIR)\extargslib.lib
	$(QUIETCMD) echo "call static $(OBJECTS)"
	$(QUIETCMD)$(LD) -out:$@  $(LDFLAGS)  $(OBJECTS)
	$(QUIETCMD)echo "use static lib"
!ELSE
svrlog.exe:$(OBJECTS)  $(DYNAMICDIR)\winlib.dll $(DYNAMICDIR)\json.dll $(DYNAMICDIR)\extargslib.dll
	$(QUIETCMD) echo "call dynamic $(OBJECTS)"
	$(QUIETCMD)$(LD) -out:$@ $(LDFLAGS) $(OBJECTS)
	$(QUIETCMD)echo "use dynamic lib"
!ENDIF	

!ELSE
svrlog.exe:$(OBJECTS)  $(DYNAMICDIR)\winlib.dll $(DYNAMICDIR)\json.dll $(DYNAMICDIR)\extargslib.dll
	$(QUIETCMD) echo "call dynamic $(OBJECTS)"
	$(QUIETCMD)$(LD) -out:$@ $(LDFLAGS) $(OBJECTS)
	$(QUIETCMD) copy /Y $(DYNAMICDIR)\extargslib.dll $(CURDIR)\extargslib.dll
	$(QUIETCMD) copy /Y $(DYNAMICDIR)\winlib.dll $(CURDIR)\winlib.dll
	$(QUIETCMD) copy /Y $(DYNAMICDIR)\json.dll $(CURDIR)\json.dll
	$(QUIETCMD)echo "use dynamic lib"
!ENDIF


.cpp.obj:
	$(QUIETCMD)$(CC) $(CFLAGS) -c -Fo$@ $<

log_file.cpp:$(CURDIR)\..\loglib\log_file.cpp
	$(QUIETCMD) copy /Y $(CURDIR)\..\loglib\log_file.cpp $@

log_rcv.cpp:$(CURDIR)\..\loglib\log_rcv.cpp
	$(QUIETCMD) copy /Y $(CURDIR)\..\loglib\log_rcv.cpp $@


main.cpp:args_options.cpp


args_options.cpp:args_options.cpp.tmpl svrlog.json $(TOPDIR)\coutput.py
	$(QUIETCMD)$(PYTHON) $(TOPDIR)\coutput.py -j $(CURDIR)\svrlog.json -i $(CURDIR)\args_options.cpp.tmpl cmdstruct | \
	 $(PYTHON) $(TOPDIR)\coutput.py -j $(CURDIR)\svrlog.json -i - -o $(CURDIR)\args_options.cpp freefunc

$(DYNAMICDIR)\extargslib.dll:
	$(QUIETCMD)cd $(TOPDIR)\common\extargslib && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=0 /f makefile.win all && cd "$(CURDIR)"

$(DYNAMICDIR)\winlib.dll:
	$(QUIETCMD)cd $(TOPDIR)\winlib && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=0 /f makefile.win all && cd "$(CURDIR)"

$(DYNAMICDIR)\json.dll:
	$(QUIETCMD)cd $(TOPDIR)\common\jsonlib && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=0 /f makefile.win all && cd "$(CURDIR)"


$(STATICDIR)\extargslib.lib:
	$(QUIETCMD)cd $(TOPDIR)\common\extargslib && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=1 /f makefile.win all && cd "$(CURDIR)"

$(STATICDIR)\winlib.lib:
	$(QUIETCMD)cd $(TOPDIR)\winlib && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=1 /f makefile.win all && cd "$(CURDIR)"

$(STATICDIR)\json.lib:
	$(QUIETCMD)cd $(TOPDIR)\common\jsonlib && $(MAKE) $(NOLOGO_MAKEFLAGS) STATICLIB=1 /f makefile.win all && cd "$(CURDIR)"

clean_winlib:
	$(QUIETCMD)cd $(TOPDIR)\winlib && $(MAKE) $(NOLOGO_MAKEFLAGS) /f makefile.win clean && cd "$(CURDIR)"

clean_json:clean_winlib
	$(QUIETCMD)cd $(TOPDIR)\common\jsonlib && $(MAKE) $(NOLOGO_MAKEFLAGS) /f makefile.win clean && cd "$(CURDIR)"

clean_extargslib: clean_json
	$(QUIETCMD)cd $(TOPDIR)\common\extargslib && $(MAKE) $(NOLOGO_MAKEFLAGS) /f makefile.win clean && cd "$(CURDIR)"


clean:clean_extargslib
	$(QUIETCMD) $(RM) *.exe *.obj 2>NUL
	$(QUIETCMD) $(RM) *.pdb *.ilk 2>NUL
	$(QUIETCMD) $(RM) args_options.cpp 2>NUL
	$(QUIETCMD) $(RM) log_file.cpp 2>NUL
	$(QUIETCMD) $(RM) log_rcv.cpp 2>NUL
	$(QUIETCMD) $(RM) *.dll 2>NUL
	$(QUIETCMD) $(RM) *.dll 2>NUL
